global.params.p1 = 1111
global.params.p2 = 2222

spring.h2.console.enabled=true
# automatically creates tables on startup and drops them when the app stops (for testing only)
spring.jpa.hibernate.ddl-auto=create-drop
# prints all SQL queries in the console (useful for debugging)
spring.jpa.show-sql=true
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
#to register this service using its IP address instead of the hostname
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#activate actuator endpoints
management.endpoints.web.exposure.include=*