#spring.application.name=gateway-service
#server.port=8888
#
#spring.config.import=optional:configserver:http://localhost:9999
##
## enable dynamic routing
#spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
#spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
spring.application.name=gateway-service
server.port=8888
eureka.instance.prefer-ip-address=true

# Config server
#spring.config.import=optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}

# Eureka
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

# Discovery locator - auto route via Eureka
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
# Expose all actuator endpoints
management.endpoints.web.exposure.include=*