spring.application.name=gateway-service
server.port=8888

spring.config.import=optional:configserver:http://localhost:9999
#
# enable dynamic routing
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true