spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: r1
              uri: http://localhost:8081
              predicates:
                - Path=/customers/**
#            - id: r2

#eureka:
#  client:
#    enabled: false
#    register-with-eureka: false
#    fetch-registry: false

server:
  port: 8888

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG